bapp/urls.py
from django.urls import path
from .views import Bloglist, Blogcreate, Blogupdate, Blogdelete, Blogdetail

app_name='bapp'
urlpatterns = [
    path('', Bloglist.as_view(), name="list"),
    path('create/', Blogcreate.as_view(), name='create'),
    path('update/<int:pk>/', Blogupdate.as_view(), name='update'),
    path('delete/<int:pk>/', Blogdelete.as_view(), name='delete'),
    path('detail/<int:pk>/', Blogdetail.as_view(), name='detail'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bapp.urls')),
]

bapp/models.py
from django.db import models

# Create your models here.

class Write(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

bapp/views.py
from .models import Write
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Write

# Create your views here.
class Bloglist(ListView):
    model = Write

class Blogcreate(CreateView):
    model = Write
    fields = ['title', 'content']
    template_name_suffix = '_create'
    success_url = '/'


class Blogupdate(UpdateView):
    model = Write
    fields = ['title', 'content']
    template_name_suffix = '_update'
    success_url = '/'

class Blogdelete(DeleteView):
    model = Write
    template_name_suffix = '_delete'
    success_url = '/'

class Blogdetail(DetailView):
    model = Write
    template_name_suffix = '_detail'

bapp/templates/bapp/write_create.html
{% extends 'base.html' %}

{% block title %}
Create
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>

    <div class="col-12 col-xl-8 col-md-4">
        <form action="" method="post">
            <div class="alert alert-primary" role="alert">
                Please insert bookmark information
            </div>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="create">
        </form>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

bapp/templates/bapp/write_delete.html
{% extends 'base.html' %}
{% block title %}
Delete
{% endblock %}


<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        {% block content %}
        <div class="alert alert-danger" role="alert">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="delete ok">
        </form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

bapp/templates/bapp/write_detail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <p class="card-text">{{object.content}}</p>
                <a href="{% url 'bapp:update' object.id %}" class="btn btn-primary">수정</a>
                <a href="{% url 'bapp:delete' object.id %}" class="btn btn-primary">삭제</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bapp/templates/bapp/write_list.html
{% extends 'base.html' %}

{% block title %}
blog list
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-6 col-md-4">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
                <th scope="col">Created</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td><a href="{% url 'bapp:detail' object.id %}">{{object.title}}</a></td>
                <td><a href="{% url 'bapp:update' object.id %}" class="btn btn-outline-info">U</a></td>
                <td><a href="{% url 'bapp:delete' object.id %}" class="btn btn-outline-danger">D</a></td>
                <td>{{object.created}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bapp/templates/bapp/write_update.html
{% extends 'base.html' %}

{% block title %}
Update
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        <div class="alert alert-info" role="alert">
            Please change bookmark information.
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="update">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}